require 'sequel'

class Movie < Sequel::Model
  def validate
    super
    errors.add(:title, 'cannot be empty') if !title || title.empty?
    errors.add(:external_id, 'cannot be empty') if !external_id
    errors.add(:image, 'cannot be empty') if !image || image.empty?
    errors.add(:release_year, 'cannot be empty') if !release_year || release_year.empty?
  end
end

# Table: movies
# Columns:
#  id          | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  external_id | integer | NOT NULL
#  title       | text    | NOT NULL
#  image       | text    | NOT NULL
# Indexes:
#  movies_pkey            | PRIMARY KEY btree (id)
#  movies_external_id_key | UNIQUE btree (external_id)
